# Generated by Django 3.1.5 on 2021-01-27 18:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 27, 18, 0, 51, 390115, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medic',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 1, 27, 18, 0, 51, 390115, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 1, 27, 18, 0, 51, 390115, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
    ]
